name: LargeRepo

on:
  pull_request:

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: 'true'
  NODE_OPTIONS: '--max_old_space_size=4096'

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - run: |
          npx nx-cloud@next start-ci-run --stop-agents-after="e2e"
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - name: Run verification
        uses: JamesHenry/parallel-bash-commands@v0.1
        with:
          cmd1: npx nx affected -t build e2e --parallel 1 --configuration=production
          cmd2: npx nx affected -t test lint --parallel 3
